apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - name: hello-node
          image: gcr.io/cloud-solutions-images/hello-node:1.0.0
          ports:
            - protocol: TCP
              name: hello-node
              containerPort: 8080
