apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - name: hello-node
          image: gcr.io/virajtest-167408/hello-node:master.32
          ports:
            - protocol: TCP
              name: hello-node
              containerPort: 8080
